# Docker provides a set of official GitHub Actions for you to use in your workflows. These official actions are reusable, easy-to-use components for building, annotating, and 
# pushing images.

name: workflow_3
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buil_push_docker_image:
    runs-on: ubuntu-latest
    environment: PROD
    
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          repository: indika-kularatne/rs_policy_service
          fetch-depth: 0  # Ensures full git history is fetched

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn clean install -DskipTests


      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: SAST analysis using SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.organization=indika-kularatne  -Dsonar.projectKey=indika-kularatne_rs_policy_service  -Dsonar.qualitygate.wait=true 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PSSWORD }}

      -  name: Build and Push
         uses: docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
           push: true
           #tags: ${{ secrets.DOCKERHUB_ORG_NAME }}/rs-policy-service:${{ github.sha }}
           tags: tuneprotectgroup/rs-policy-service:${{ github.sha }}
         env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PSSWORD }}
