# Docker provides a set of official GitHub Actions for you to use in your workflows. These official actions are reusable, easy-to-use components for building, annotating, and 
# pushing images.

name: workflow_3
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buil_push_docker_image:
    runs-on: ubuntu-latest
    environment: PROD
    
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          repository: rs_policy_service/rs_policy_service
          fetch-depth: 0  # Ensures full git history is fetched

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn clean install -DskipTests

      #- name: SonarQube Scan
        #uses: sonarsource/sonarqube-scan-action@v2.1.0
        #env:
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=indika-kularatne \
          -Dsonar.projectKey=indika-kularatne_rs_policy_service \
          -Dsonar.qualitygate.wait=true 

        #run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=indika-kularatne_rs_policy_service -Dsonar.login=0f187069eddb7b5f72593d7fdf48dcb30dc16b1d
        
