# Docker provides a set of official GitHub Actions for you to use in your workflows. These official actions are reusable, easy-to-use components for building, annotating, and 
# pushing images.

name: workflow_1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buil_push_docker_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          repository: TuneDemo/rs_policy_service

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run : mvn -B package --file pom.xml

